import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import '../assets/styles/globals.css';

const roboto = Roboto({
	subsets: ['latin'],
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Aluritter',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-br'>
			<body className={roboto.className}>{children}</body>
		</html>
	);
}
